- .github/workflows/CI.yml
> 🔀 :: (#1) CI 설정

- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/property/AwsS3Properties.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/property/AwsSesProperties.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/property/JwtProperties.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/property/config/ConfigurationPropertiesConfig.java
- yapaghetti-infrastructure/src/main/resources/application.yml
> 🔀 :: (#12) Property 클래스 파일 정의

- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/property/AwsS3Properties.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/property/AwsSesProperties.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/property/JwtProperties.java
> 🔀 :: (#16) 생성자 어노테이션 변경

- yapaghetti-infrastructure/build.gradle
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/error/GlobalErrorCode.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/exception/ImageExtensionInvalidException.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/exception/ImageNotFoundException.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/infrastructure/s3/.gitKeep
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/infrastructure/s3/AwsS3Adapter.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/infrastructure/s3/AwsS3Port.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/infrastructure/s3/type/ImageType.java
> 🔀 :: (#5) AwsS3Adapter 추가

- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/api/SignInPort.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/domain/User.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/error/UserErrorCode.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/spi/CommandUserPort.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/spi/QueryUserPort.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/usecase/SignInUseCase.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/user/api/SignInPort.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/user/spi/CommandUserPort.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/user/spi/QueryUserPort.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/user/usecase/SignInUseCase.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/persistence/CompanyPersistenceAdapter.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/persistence/CompanyRepository.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/persistence/entity/CompanyAuthority.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/persistence/entity/CompanyEntity.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/company/persistence/entity/CompanyAuthority.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/persistence/UserPersistenceAdapter.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/security/principle/AuthDetailsService.java
> 🔀 :: (#20) 패키지 정리

- .github/workflows/CI.yml
- build.gradle
- yapaghetti-application/build.gradle
- yapaghetti-infrastructure/build.gradle
> 🔀 :: (#30) CodeCov 세팅

- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/persistence/UserQuerydslExtension.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/persistence/UserQuerydslImpl.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/persistence/UserRepository.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/querydsl/QuerydslConfig.java
> 🔀 :: (#33) querydsl setting

- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/tag/domain/TagType.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/persistence/entity/CompanyEntity.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/persistence/entity/DocumentEntity.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/feedback/persistence/entity/FeedBackEntity.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/my_skill/persistence/MySkillPersistenceAdapter.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/my_skill/persistence/MySkillRepository.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/my_skill/persistence/entity/MySkillEntity.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/my_skill/persistence/entity/MySkillEntityId.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/tag/persistence/TagPersistenceAdapter.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/tag/persistence/TagRepository.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/tag/persistence/entity/TagEntity.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/persistence/entity/UserEntity.java
> 🔀 :: (#41) 태그 & 마이스킬 엔티티

- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/persistence/TeacherPersistenceAdapter.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/persistence/TeacherRepository.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/persistence/entity/TeacherEntity.java
> 🔀 :: (#45) 선생님 Entity

- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/domain/UserRole.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/security/SecurityConfig.java
> 🔀 :: (#57) COMPANY UserRole 삭제

- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/api/QueryPublicDocumentPort.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/api/dto/response/QueryPublicDocumentResponse.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/error/DocumentErrorCode.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/exception/DocumentNotFoundException.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/spi/QueryDocumentPort.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/QueryPublicDocumentUseCase.java
- yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/QueryPublicDocumentTest.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/mapper/DocumentMapper.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/persistence/DocumentPersistenceAdapter.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/persistence/DocumentRepository.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/presentation/DocumentWebAdapter.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/security/SecurityConfig.java
> 🔀 :: (#59) 공개 문서 조회 API

- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/domain/Student.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/tag/error/TagErrorCode.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/tag/exception/TagNotFoundException.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/persistence/CompanyRepository.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/persistence/DocumentRepository.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/mapper/StudentMapper.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/persistence/entity/StudentEntity.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/tag/persistence/TagPersistenceAdapter.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/tag/persistence/TagRepository.java
> 🔀 :: (#55) 학생 aggregate + mapper + 자잘한 수정

- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/api/CopyPublicDocumentPort.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/spi/QueryDocumentPort.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/CopyPublicDocumentUseCase.java
- yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/CopyPublicDocumentTest.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/persistence/DocumentPersistenceAdapter.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/persistence/DocumentRepository.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/presentation/DocumentWebAdapter.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/security/SecurityConfig.java
> 🔀 :: (#62) 공개 문서 로컬로 복사 API

- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/domain/Document.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/domain/Student.java
> 🔀 :: (#67) Aggregate 불변객체로 변경

- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/tag/api/AddTagPort.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/tag/api/dto/request/DomainAddTagRequest.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/tag/domain/Tag.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/tag/error/TagErrorCode.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/tag/exception/AlreadyExistsTagException.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/tag/spi/CommandTagPort.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/tag/spi/QueryTagPort.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/tag/usecase/AddTagUseCase.java
- yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/tag/usecase/AddTagUseCaseTest.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/tag/mapper/TagMapper.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/tag/persistence/TagPersistenceAdapter.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/tag/persistence/TagRepository.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/tag/persistence/entity/TagEntity.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/tag/presentation/TagWebAdapter.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/tag/presentation/dto/request/WebAddTagRequest.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/security/SecurityConfig.java
> 🔀 :: (#8) 태그 생성 기능 개발

- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/api/QueryProtectedDocumentUrlPort.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/api/dto/response/QueryProtectedDocumentUrlResponse.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/spi/QueryDocumentPort.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/CopyPublicDocumentUseCase.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/QueryProtectedDocumentUrlUseCase.java
- yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/CopyPublicDocumentTest.java
- yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/QueryProtectedDocumentUrlTest.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/persistence/DocumentPersistenceAdapter.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/presentation/DocumentWebAdapter.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/security/SecurityConfig.java
> 🔀 :: (#66) 공개 문서 링크 받아오기 API

- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/api/DeleteLocalDocumentPort.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/DeleteLocalDocumentUseCase.java
- yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/CopyPublicDocumentTest.java
- yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/DeleteLocalDocumentUseCaseTest.java
- yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/DeletePublicDocumentTest.java
- yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/QueryPublicDocumentTest.java
- yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/UpdateLocalDocumentTest.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/presentation/DocumentWebAdapter.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/security/SecurityConfig.java
> 🔀 :: (#76) 로컬 문서 삭제 API

- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/api/QueryLocalDocumentPort.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/api/QueryPublicDocumentPort.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/api/dto/response/QueryDocumentResponse.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/QueryLocalDocumentUseCase.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/QueryPublicDocumentUseCase.java
- yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/QueryLocalDocumentUseCaseTest.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/presentation/DocumentWebAdapter.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/security/SecurityConfig.java
> 🔀 :: (#79) 로컬 문서 조회 API

- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/my_skill/spi/CommandMySkillPort.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/tag/usecase/AddMySkillUseCase.java
- yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/tag/usecase/AddMySkillUseCaseTest.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/my_skill/persistence/MySkillPersistenceAdapter.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/my_skill/persistence/MySkillRepository.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/my_skill/persistence/entity/MySkillEntityId.java
> 🔀 :: (#90) 기술 태그 설정 miss

- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/api/UpdateUserInformationPort.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/api/dto/request/DomainUpdateUserInformationRequest.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/domain/User.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/usecase/UpdateUserInformationUseCase.java
- yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/user/usecase/UpdateUserInformationUseCaseTest.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/presentation/UserWebAdapter.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/presentation/dto/request/WebUpdateUserInformationRequest.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/security/SecurityConfig.java
> 🔀 :: (#81) 유저 정보 수정 Api

- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/api/CancelStayDocumentPort.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/domain/Document.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/spi/CommandDocumentPort.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/spi/DocumentSecurityPort.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/CancelStayDocumentUseCase.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/UpdateLocalDocumentUseCase.java
- yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/CancelStayDocumentUseCaseTest.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/persistence/DocumentPersistenceAdapter.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/persistence/entity/DocumentEntity.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/presentation/DocumentWebAdapter.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/annotation/config/GlobalComponentScan.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/security/SecurityConfig.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/security/SecurityFacadeAdapter.java
> 🔀 :: (#72) 공개 요청 문서 취소 API

- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/spi/StudentPort.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/api/DeleteStudentPort.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/spi/TeacherCommandStudentPort.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/spi/TeacherQueryStudentPort.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/usecase/DeleteStudentUseCase.java
- yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/teacher/usecase/DeleteStudentTest.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/persistence/StudentPersistenceAdapter.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/presentation/TeacherWebAdapter.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/security/SecurityConfig.java
> 🔀 :: (#23) 학생 탈퇴 Api

- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/domain/Company.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/mapper/CompanyMapper.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/persistence/entity/CompanyEntity.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/persistence/UserRepository.java
> 🔀 :: (#115) 기업 문서 확인 시작일과 마감일 추가

- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/tag/spi/QueryTagPort.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/tag/usecase/AddTagUseCase.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/tag/usecase/DeleteTagUseCase.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/tag/usecase/SetMajorTagUseCase.java
- yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/tag/usecase/AddTagUseCaseTest.java
- yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/tag/usecase/DeleteTagUseCaseTest.java
- yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/tag/usecase/SetMajorTagUseCaseTest.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/persistence/StudentPersistenceAdapter.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/tag/persistence/TagPersistenceAdapter.java
> 🔀 :: (#108) exists와 관련된 Exception Adapter로 이동하기

- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/spi/QueryDocumentPort.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/QueryPublicDocumentUseCase.java
- yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/QueryPublicDocumentTest.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/persistence/DocumentPersistenceAdapter.java
> 🔀 :: (#124) 공개 문서 조회 비즈니스 로직 수정

- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/api/ApproveStayDocumentPort.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/api/dto/response/DocumentElement.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/domain/Document.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/ApproveStayDocumentUseCase.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/CopyPublicDocumentUseCase.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/CreateLocalDocumentUseCase.java
- yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/ApproveStayDocumentTest.java
- yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/CopyPublicDocumentTest.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/mapper/DocumentMapper.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/persistence/entity/DocumentEntity.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/presentation/DocumentWebAdapter.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/security/SecurityConfig.java
> 🔀 :: (#88) 공개 요청 승인 API

- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/api/RejectStayDocumentPort.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/domain/Document.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/CopyPublicDocumentUseCase.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/CreateLocalDocumentUseCase.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/RejectStayDocumentUseCase.java
- yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/ApproveStayDocumentTest.java
- yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/CopyPublicDocumentTest.java
- yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/RejectStayDocumentTest.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/mapper/DocumentMapper.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/persistence/entity/DocumentEntity.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/presentation/DocumentWebAdapter.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/security/SecurityConfig.java
> 🔀 :: (#87) 공개 요청 거부 API

- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/api/TokenRefreshPort.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/api/dto/response/TokenRefreshResponse.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/domain/RefreshToken.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/error/UserErrorCode.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/exception/RefreshTokenNotFoundException.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/spi/CommandRefreshTokenPort.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/spi/QueryRefreshTokenPort.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/spi/RefreshTokenPort.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/spi/UserJwtPort.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/spi/dto/SpiTokenResponse.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/usecase/SignInUseCase.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/usecase/TokenRefreshUseCase.java
- yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/user/usecase/SignInUseCaseTest.java
- yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/user/usecase/TokenRefreshUseCaseTest.java
- yapaghetti-infrastructure/build.gradle
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/mapper/RefreshTokenMapper.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/persistence/RefreshTokenPersistenceAdapter.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/persistence/RefreshTokenRepository.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/persistence/entity/RefreshTokenEntity.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/presentation/UserWebAdapter.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/security/SecurityConfig.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/security/jwt/JwtTokenProvider.java
> 🔀 :: (#29) 토큰 리프레시

- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/api/QueryStayAndPublicDocumentPreviewPort.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/api/dto/response/QueryStayAndPublicDocumentPreviewResponse.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/api/dto/response/StayAndPublicDocumentElement.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/spi/DocumentQueryStudentPort.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/spi/QueryDocumentPort.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/QueryStayAndPublicDocumentPreviewUseCase.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/spi/StudentPort.java
- yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/QueryStayAndPublicDocumentPreviewUseCaseTest.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/persistence/DocumentPersistenceAdapter.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/persistence/DocumentRepository.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/presentation/DocumentWebAdapter.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/persistence/StudentPersistenceAdapter.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/security/SecurityConfig.java
> 🔀 :: (#127) 공개 / 대기 문서 미리보기 API

- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/spi/QueryCompanyPort.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/usecase/UpdateCompanyNameUseCase.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/api/GetCompanyDetailPort.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/api/dto/response/CompanyDetailResponse.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/spi/TeacherQueryCompanyPort.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/spi/TeacherQueryUserPort.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/usecase/DeleteCompanyUseCase.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/usecase/GetCompanyDetailUseCase.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/spi/UserPort.java
- yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/company/usecase/UpdateCompanyNameUseCaseTest.java
- yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/teacher/usecase/DeleteCompanyTest.java
- yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/teacher/usecase/GetCompanyDetailTest.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/persistence/CompanyPersistenceAdapter.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/presentation/TeacherWebAdapter.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/security/SecurityConfig.java
> 🔀 :: (#120) 기업 정보 상세 보기 

- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/api/QueryCompanyListPort.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/api/dto/response/CompanyElement.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/api/dto/response/CompanyListResponse.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/spi/TeacherQueryCompanyPort.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/usecase/QueryCompanyListUseCase.java
- yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/teacher/usecase/QueryCompanyListTest.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/persistence/CompanyPersistenceAdapter.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/presentation/TeacherWebAdapter.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/security/SecurityConfig.java
> 🔀 :: (#117) 회사 검색

- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/spi/DocumentQueryTagPort.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/QueryLocalDocumentListUseCase.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/tag/spi/TagPort.java
- yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/QueryLocalDocumentListUseCaseTest.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/presentation/DocumentWebAdapter.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/tag/persistence/TagPersistenceAdapter.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/mapper/RefreshTokenMapper.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/security/jwt/JwtTokenProvider.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/infrastructure/ses/AwsSESConfig.java
> 🔀 :: (#138) 로컬 문서 리스트 조회 Api 버그 수정 & 기타 에러 수정

- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/presentation/TeacherWebAdapter.java
> 🔀 :: (#156) TeacherWebAdapter 수정

- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/auth/api/VerifyAuthCodePort.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/auth/api/VerifyEmailAuthCodePort.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/auth/domain/AuthCodeType.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/auth/usecase/VerifyAuthCodeUseCase.java
- yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/auth/usecase/VerifyAuthCodeUseCaseTest.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/auth/presentation/AuthWebAdapter.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/security/SecurityConfig.java
> 🔀 :: (#154) 인증번호 확인 통합

- .github/workflows/CD.yml
> 🔀 :: (#161) CD 설정

- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/spi/UserPort.java
> 🔀 :: (#171) StudentCommandUserPort를 UserPort에 extends

- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/image/presentation/ImageWebAdapter.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/infrastructure/s3/AwsS3Adapter.java
> 🔀 :: (#173) 이미지 업로드 에러 수정

- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/config/WebConfig.java
> 🔀 :: (#176) WebConfig 설정

- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/image/presentation/ImageWebAdapter.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/infrastructure/s3/AwsS3Adapter.java
> 🔀 :: (#178) 이미지 업로드 이후 임시파일 삭제 & method 명 수정

- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/error/filter/GlobalErrorFilter.java
> 🔀 :: (#181) ErrorFilter에서 InternalServerError 일 때 StackTrace를 출력

- yapaghetti-infrastructure/src/main/resources/application.yml
> 🔀 :: (#183) Redis password 설정

- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/api/dto/response/CompanyElement.java
- yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/teacher/usecase/QueryCompanyListTest.java
> 🔀 : (#189) Type 변경

- README.md
> 🔀 :: (#192) project structure

- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/error/UserErrorCode.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/exception/AlreadyVisitException.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/usecase/FirstPasswordUpdateUseCase.java
> 🔀 :: (#187) 최초 비밀번호 수정 Api 체크

- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/tag/presentation/dto/request/WebAddTagRequest.java
> 🔀 :: (#196) @Max는 숫자 타입에, String valid check는 @Size로!

- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/api/dto/response/StudentElementByGradeClassNum.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/persistence/StudentPersistenceAdapter.java
> 🔀 :: (#180) 학생 리스트 오류

- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/api/dto/response/StudentDetailResponse.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/persistence/StudentPersistenceAdapter.java
> 🔀 :: (#201) 학생 상세보기 오류 

- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/api/dto/request/DomainNewCompanyRequest.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/api/dto/request/DomainUpdateCompanyRequest.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/api/dto/response/CompanyDetailResponse.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/spi/TeacherCommandUserPort.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/usecase/CreateCompanyUseCase.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/usecase/GetCompanyDetailUseCase.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/usecase/UpdateCompanyUseCase.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/domain/User.java
- yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/teacher/usecase/UpdateCompanyTest.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/presentation/TeacherWebAdapter.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/presentation/dto/request/WebCreateCompanyRequest.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/presentation/dto/request/WebCreateFeedbackRequest.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/presentation/dto/request/WebUpdateCompanyRequest.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/persistence/UserPersistenceAdapter.java
close #198 
Teacher 부분에서 API 명세에 맞지 않거나, 잘못된 부분을 포괄적으로 수정하였습니다.
Company에 값을 새로 넣거나 변경하는 경우에 발생하는 예외에 대해서는 다른 이슈를 통해서 올리도록 하겠습니다.
> 🔀 :: (#198) Teacher 부분 코드 정리

- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/mapper/StudentMapper.java
> 🔀 :: (#204) 학생 삭제 오류 

- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/mapper/CompanyMapper.java
> 🔀 :: (#203) 기업 삭제 오류 해결

- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/api/dto/response/StudentDetailResponse.java
- yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/teacher/usecase/QueryStudentDetailTest.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/persistence/StudentPersistenceAdapter.java
> 🔀 :: (#207) 학생 상세 보기 이미지 url 추가

- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/persistence/StudentPersistenceAdapter.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/presentation/TeacherWebAdapter.java
> 🔀 :: (#180) 학생 전체 리스트 수정

- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/persistence/StudentPersistenceAdapter.java
> 🔀 :: (#180) 문서 없는 학생도 리스트에 나오게 변경

- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/usecase/CreateCompanyUseCase.java
- yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/teacher/usecase/CreateCompanyUseCaseTest.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/mapper/CompanyMapper.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/persistence/CompanyPersistenceAdapter.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/persistence/entity/CompanyEntity.java
cascade로 해결했는데 왜 그렇게 된건지 아직 찾아보는중이라서 아시면 댓글 달아주세요...
close #206
> 🔀 :: (#206) 기업 생성 에러 해결

- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/persistence/StudentPersistenceAdapter.java
> 🔀 :: (#180) 학생 리스트 중복 제거

- .gitignore
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/my_skill/persistence/entity/MySkillEntity.java
close #217 
2번째로 어프루브 누른사람이 머지 시켜줘
* 추가사항
* .gitignore : src/generated git ignore에 추가
* MySkillEntity  : uniqueConstraints 속성 추가
> 🔀 :: (#217) myskill 엔티티 unique 속성 추가

- .github/workflows/CD.yml
> 🔀 :: (#215) version 수정

- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/QueryLocalDocumentUseCase.java
- yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/QueryLocalDocumentUseCaseTest.java
> 🔀 :: (#225) Local Document 조회 에러 수정

- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/presentation/dto/request/WebCreateLocalDocumentRequest.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/presentation/dto/request/WebUpdateLocalDocumentRequest.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/presentation/dto/request/WebUpdateStayDocumentRequest.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/presentation/dto/request/WebFirstPasswordUpdateRequest.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/presentation/dto/request/WebSignInRequest.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/presentation/dto/request/WebUpdateUserInformationRequest.java
close #223 
놓친 부분이나, 사이즈가 알맞지 않다고 생각하는 부분 있으시면 말씀해주세요!
> 🔀 :: (#223) @Size 설정

- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/api/dto/response/CompanyDetailResponse.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/usecase/GetCompanyDetailUseCase.java
- yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/teacher/usecase/GetCompanyDetailUseCaseTest.java
> 🔀 :: (#220) isMou 추가

- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/usecase/CreateFeedbackUseCase.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/persistence/DocumentPersistenceAdapter.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/persistence/DocumentRepository.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/persistence/entity/DocumentEntity.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/feedback/mapper/FeedbackMapper.java
> 🔀 :: (#210) 피드백 추가 오류

- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/thirdparty/s3/AwsS3Adapter.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/thirdparty/ses/AwsSESAdapter.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/thirdparty/ses/AwsSESConfig.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/thirdparty/sms/CoolSmsAdapter.java
> 🔀 :: (#228) infrastructure -> thirdparty로 패키지명 변경

- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/mapper/DocumentMapper.java
> 🔀 :: (#230) 공개 요청 취소 Api 버그 해결

- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/api/dto/request/DomainUpdateCompanyNameRequest.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/spi/CompanyCommandUserPort.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/spi/CompanyQueryUserPort.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/usecase/UpdateCompanyNameUseCase.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/spi/UserPort.java
- yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/company/usecase/UpdateCompanyNameUseCaseTest.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/presentation/CompanyWebAdapter.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/presentation/dto/request/WebUpdateCompanyInformationRequest.java
> 🔀 :: (#232) 기업 정보 수정 Api 변경

- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/annotation/config/AnnotationConfig.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/filter/FilterConfig.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/security/SecurityConfig.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/web/WebConfig.java
> 🔀 :: (#175) 패키지 구조 통일

- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/api/dto/response/StudentElement.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/persistence/StudentPersistenceAdapter.java
> 🔀 :: (#240) 문서 Id 넘겨주기

- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/api/QueryCompanyInfoPort.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/api/dto/response/QueryCompanyInfoResponse.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/usecase/QueryCompanyInfoUseCase.java
- yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/company/usecase/QueryCompanyInfoUseCaseTest.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/presentation/CompanyWebAdapter.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/security/SecurityConfig.java
> 🔀 :: (#239) 기업 정보 조회 Api 구현

- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/error/GlobalErrorCode.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/exception/SendEmailRejectedException.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/thirdparty/ses/AwsSESAdapter.java
close #243 
템플릿 생기면 그때 수정하겠습니다.
> 🔀 :: (#243) 이메일 전송 버그

- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/usecase/UpdateCompanyNameUseCase.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/api/dto/request/DomainUpdateCompanyRequest.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/usecase/UpdateCompanyUseCase.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/domain/User.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/presentation/TeacherWebAdapter.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/presentation/dto/request/WebUpdateCompanyRequest.java
close #247 
- TEACHER
- 맴버 변수 생성
- COMPANY
- 변수 재정의
> 🔀 :: (#247) 회사 업데이트 수정

- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/api/CreateLocalDocumentPort.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/api/dto/request/DomainCreateLocalDocumentRequest.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/api/dto/response/CreateLocalDocumentResponse.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/spi/CommandDocumentPort.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/CreateLocalDocumentUseCase.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/persistence/DocumentPersistenceAdapter.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/presentation/DocumentWebAdapter.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/presentation/dto/request/WebCreateLocalDocumentRequest.java
> 🔀 :: (#249) 로컬문서 생성 시 response 추가

- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/QueryStayDocumentUseCase.java
- yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/QueryStayDocumentUseCaseTest.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/presentation/DocumentWebAdapter.java
> 🔀 :: (#251) 대기문서 조회 api studentId로 조회

- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/auth/enums/EmailType.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/auth/spi/SendMailPort.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/auth/usecase/SendEmailAuthCodeUseCase.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/spi/DocumentQueryUserPort.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/RequestLocalDocumentToPublicUseCase.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/spi/TeacherCommandUserPort.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/usecase/ChangeCompanyPasswordUseCase.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/usecase/CreateCompanyUseCase.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/usecase/CreateFeedbackUseCase.java
- yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/RequestLocalDocumentToPublicUseCaseTest.java
- yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/teacher/usecase/CreateCompanyUseCaseTest.java
- yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/teacher/usecase/CreateFeedbackUseCaseTest.java
- yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/teacher/usecase/ResetPasswordTest.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/persistence/UserPersistenceAdapter.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/persistence/UserRepository.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/thirdparty/ses/AwsSESAdapter.java
> 🔀 :: (#253) 각종 이메일 보내기 & 이메일 템플릿 설정

- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/auth/spi/RandomStringPort.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/api/BetaCreateUserPort.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/api/dto/response/BetaCreateUserResponse.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/spi/StudentQueryUserPort.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/spi/StudentRandomStringPort.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/spi/StudentSecurityPort.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/usecase/BetaCreateUserUseCase.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/error/UserErrorCode.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/exception/UserAlreadyExistsException.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/persistence/StudentPersistenceAdapter.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/persistence/entity/StudentEntity.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/presentation/StudentWebAdapter.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/presentation/dto/request/BetaCreateStudentRequest.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/persistence/UserPersistenceAdapter.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/security/SecurityConfig.java
> 🔀 :: (#258) 베타 테스트용 학생 생성 !긴급

- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/spi/DocumentCommandFeedbackPort.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/ApproveStayDocumentUseCase.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/feedback/spi/CommandFeedbackPort.java
- yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/ApproveStayDocumentUseCaseTest.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/persistence/entity/DocumentEntity.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/feedback/persistence/FeedbackPersistenceAdapter.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/feedback/persistence/FeedbackRepository.java
close #255 
대기 문서에서 공개 문서로 수정할 경우, 선생님이 모든 피드백을 확인했다는 가정 하에 모든 피드백을 삭제하게 됩니다.
기존에 있던 공개 문서는 삭제 처리 됩니다.
> 🔀 :: (#255) 대기 문서 -> 공개 문서

- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/api/CreateLocalDocumentPort.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/api/dto/request/DomainCreateDocumentRequest.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/CreateLocalDocumentUseCase.java
- yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/CreateLocalDocumentUseCaseTest.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/presentation/DocumentWebAdapter.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/presentation/dto/request/WebCreateLocalDocumentRequest.java
> 🔀 :: (#261) 로컬 문서 생성 시 request 추가

- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/api/dto/response/MyInfoResponse.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/api/dto/response/MySkillElement.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/spi/StudentQueryMySkillPort.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/usecase/QueryMyInfoUseCase.java
- yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/student/usecase/GetMyInfoUseCaseTest.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/my_skill/persistence/MySkillPersistenceAdapter.java
> 🔀 :: (#264) 프론트 요구사항 반영

- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/feedback/persistence/FeedbackPersistenceAdapter.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/my_skill/persistence/MySkillPersistenceAdapter.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/persistence/StudentPersistenceAdapter.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/aop/TransactionAspect.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/db/TransactionConfiguration.java
> 🔀 :: (#266) TransactionAspect가 정상적으로 동작하지 않음

- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/api/dto/response/StudentElementByGradeClassNum.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/persistence/StudentPersistenceAdapter.java
> 🔀 :: (#268) 학생 리스트 보기 값 변경

- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/feedback/spi/CommandFeedbackPort.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/api/DeleteFeedbackPort.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/api/dto/request/DomainDeleteFeedbackRequest.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/spi/TeacherCommandFeedbackPort.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/usecase/CreateFeedbackUseCase.java
- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/usecase/DeleteFeedbackUseCase.java
- yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/teacher/usecase/TeacherDeleteFeedbackUseCaseTest.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/feedback/persistence/FeedbackPersistenceAdapter.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/feedback/persistence/FeedbackRepository.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/presentation/TeacherWebAdapter.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/presentation/dto/request/WebDeleteFeedbackRequest.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/security/SecurityConfig.java
> 🔀 :: (#271) 선생님 피드백 삭제  API

- yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/api/dto/response/StudentElementByGradeClassNum.java
- yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/persistence/StudentPersistenceAdapter.java
> 🔀 :: (#273) 학생 리스트 조건 변경
